### ISSUE TITLE
Bootstrapping the CFTs with affine Lie algebraic symmetry

### ISSUE THREAD

**Issue by CSJgroup** [cbehan/pycftboot#13]
Sir,
Can we write the PyCFTBoot for bootstrapping the CFTs with affine Lie algebraic symmetry(Kac-Moody algebra) like g_k WZW models?

**Comment by cbehan** [comment]
Since you mention WZW models, are you mainly interested in cases where you can use the Sugawara construction to go from the affine algebra to the enveloping Virasoro algebra? If so, the structure is highly constrained by Knizhnik-Zamolodchikov equations and it's not clear to me that you would need to use the numerical bootstrap.

If, on the other hand, you want to consider a stress tensor that's not the Sugawara one, it's going to be very expensive to compute the blocks. There might be some recent breakthroughs in this area along the lines of 1511.04065 but they are pretty far outside the scope of this code.

**Comment by CSJgroup** [comment]
Sir, 
We want to reproduce the article arXiv:1708.08815v2.

**Comment by cbehan** [comment]
Ok, so you want to do the modular bootstrap. This should be handled by a separate program. Not a patch for this one.

**Comment by ZJR19930222** [comment]
os.system(unisolve_path + " -H1 -o" + str(prec) + " -Oc -Ga tmp.pol > tmp.spectrum")
unisolve is what?
I need your help

**Comment by ZJR19930222** [comment]
there is no executable file named unisolve? 
is it in boost or in symengine?
I can run all examples in pycftboot well except 4.3

**Comment by cbehan** [comment]
Closing to keep this discussion in the dedicated issue.
