### ISSUE TITLE
How to use hot-starting in pycftboot?

### ISSUE THREAD

**Issue by CSJgroup** [cbehan/pycftboot#15]
Sir,
Can we use hot-starting in PyCFTBoot?
Can we turn off or turn on some parameters associated with SDPB like findPrimalFeasible=false etc?

**Comment by cbehan** [comment]
Yes. Checkpoints were buggy at certain points in the early days so I disabled them for SDPB1. But if you have SDPB2 installed and set sdpb_version=2 in common.py, it should work.Specifically, sdp.bisect() will do a long run in the first iteration and then hotstart from the last checkpoint in all later iterations.

PyCFTBoot has sdp.set_option() for changing any numerical parameter. I didn't add any method for changing the boolean parameters because that changes the nature of the problem. I.e. sdp.iterate() is designed to be used when you're testing feasibility and sdp.solution_functional() is designed to be used otherwise. For maximum flexibility, you can call SDPB on XML files manually and only use PyCFTBoot to create them with sdp.write_xml().
